"""
    Program 1: printing a song or poem
"""
print('Lifelight from Super Smash Bros. Ultimate\n\n')
print('Colors weave into a spire of flame')
print('Distant sparks call to a past still unnamed')
print('Bear this torch against the cold of the night')
print('Search your soul and reawaken the undying light!\n')
print('On that day')
print('When the sky fell away')
print('Our world came to an end')
print('In our eyes')
print('Did a fading sun rise in the dark?')
print('Glimmering shadows')
print('Silence grows')
print('In the spaces between')
print('Stretching out beyond time')
print('Rising up as a chorus of souls find a voice')
print('Flickering through the void!')
print('These little sparks')
print('Cling onto life')
print('Everyone caught in the struggle')
print('And then the storms of change')
print('They fan the flames')
print('Scattering ashes through the wind!\n')
print('Every soul contains a whisper of light')
print('Gleaming faintly as it dwindles from sight')
print('No escape')
print('No greater fate to be made!')
print('In the end, the chains of time will not break\n')
print('Colors weave into a spire of flame')
print('Distant sparks call to a past still unnamed')
print('Bear this torch against the cold of the night')
print('Search your soul and reawaken the undying light!\n')
print('As fate spins')
print('A thread without end')
print('New life draws its first breath')
print('Blossoming in a soil reclaimed from the past')
print('Where destiny holds fast!')
print('Here where we stand')
print('Hand clenched in hand')
print('Everyone caught in the struggle')
print('This is the day we finally find our way')
print('Stepping into our tomorrow!\n')
print('Every soul contains a whisper of light')
print('Growing louder as it calls to unite')
print('From the distance sings a chorus of souls')
print('Rising slowly stirring heat from the coals\n')
print('Colors weave into a spire of flame')
print('Distant sparks call to a past still unnamed')
print('Bear this torch against the cold of the night')
print('Light will guide you on your way to the ultimate fight!\n')
print('Every soul contains a whisper of light')
print('Growing louder as it calls to unite')
print('From the distance sings a chorus of souls')
print('Rising slowly stirring heat from the coals\n')
print('Colors weave into a spire of flame')
print('Distant sparks call to a past still unnamed')
print('Bear this torch against the cold of the night')
print('Light will guide you on your way to the ultimate fight!')
